name: Scheduled Scan & Rebuild Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - v2-apache
        - v3-nginx

    steps:
      - uses: actions/checkout@v1

      - name: Pull owasp/modsecurity:$(cut -f2 -d- ${{ matrix.image }}
        run: docker pull owasp/modsecurity:$(cut -f2 -d- ${{ matrix.image }})

      - name: Scan with Phonito Security
        id: phonito_scanner
        uses: phonito/phonito-scanner-action@master
        with:
          image: owasp/modsecurity:$(cut -f2 -d- ${{ matrix.image }})
          phonito-token: '${{ secrets.PHONITO_TOKEN }}'
        
      - name: Build ${{ matrix.image }}
        if: failure()
        run: docker build . -f ${{ matrix.image }}/Dockerfile
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -v)
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -vv)
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -vvv)
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -vvvv)

      - uses: azure/docker-login@v1
        if: failure()
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}

      - name: Push ${{ matrix.image }}
        if: failure()
        run: echo "Pushing images"
#        run: docker push owasp/modsecurity
